#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo "############################################################"
echo "# install jupyter using conda                              #"
echo "############################################################"

if [ -n "${DIB_JUPYTERLAB_VER}" ]; then
    $(conda info --base)/bin/python3 -m pip install jupyterlab==${DIB_JUPYTERLAB_VER}
else
    $(conda info --base)/bin/python3 -m pip install jupyterlab
fi

JP_PATH=$(conda run which jupyter)

# generate start scripts
cat <<EOF >/usr/local/bin/start_jupyter_lab
#!/bin/bash
${JP_PATH} lab --allow-root --config /root/.jupyter/jupyter_lab_config.py
EOF

chmod +x /usr/local/bin/start_jupyter_lab
