#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

echo "############################################################"
echo "# root login only                                          #"
echo "############################################################"

cat >/etc/cloud/cloud.cfg.d/05-dib-root-login.cfg <<EOF
# remove default user
users: []
# enable root login
disable_root: false
EOF
