#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

echo "############################################################"
echo "# enable ssh password login                                #"
echo "############################################################"

cat >/etc/cloud/cloud.cfg.d/05-dib-pwauth-login.cfg <<EOF
# enable password login
ssh_pwauth: 1
EOF
