#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo ">> remove default users"

cat >/etc/cloud/cloud.cfg.d/05-dib-remove-default-users.cfg <<EOF
# remove default users
users: []
EOF
