#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Copy rclone file from HOST"

if [ -n "${RCLONE_FILE}" ]; then
    cp ${RCLONE_FILE} ${TMP_MOUNT_PATH}/tmp/$(basename ${RCLONE_FILE})
else
    echo "ERROR: RCLONE_FILE is not set."
fi
