#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo ">> install filebrowser"

## extract filebrowser and move to PATH
tar -xvf /tmp/filebrowser.tar.gz -C /tmp
cp /tmp/filebrowser /usr/local/bin/
