#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Install rclone"

sudo dpkg -i /tmp/$(basename ${RCLONE_FILE})

# Rclone as Unix mount helper
sudo ln -s /usr/bin/rclone /sbin/mount.rclone

# Set up rclone config
mkdir -p /root/.config/rclone
cat <<EOF >/root/.config/rclone/rclone.conf
[public-data]
type = s3
provider = Other
env_auth = true
EOF
