#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
	set -x
fi
set -o errexit
set -o nounset
set -o pipefail

echo "############################################################"
echo "# GPUDirect perftest                                       #"
echo "############################################################"

#verify cuda path

if [ -d "${DIB_CUDA_PATH}" ]; then
	echo "DIB_CUDA_PATH is set."
else
	echo "ERROR: DIB_CUDA_PATH is not set!"
fi

# comparing chroot kernel with host kernel
CHROOT_KERNEL=$(dpkg -l | awk '/^.i +linux-(im)/&& $2~/[0-9]/{print substr($2,13)}')
HOST_KERNEL=$(uname -r)
if [ "$CHROOT_KERNEL" != "$HOST_KERNEL" ]; then
	"ERROR: kernel mismatch!"
	exit 1
fi

unset ARCH

# perftest
git clone https://github.com/linux-rdma/perftest /tmp/perftest
cd /tmp/perftest
./autogen.sh
./configure CUDA_PATH=${DIB_CUDA_PATH} CUDA_H_PATH=${DIB_CUDA_PATH}/targets/x86_64-linux/include/cuda.h
make install

# clean
export ARCH=amd64
rm -Rf /tmp/perftest
