#!/bin/bash

install-openstack-client() {
    if command -v openstack &>/dev/null; then
        return
    fi

    pip install python-openstackclient
}

upload() {
    install-openstack-client
    eval openstack image create \
        --container-format bare \
        --progress \
        --public $@
}

image-linux() {
    name="$1"
    os_distro="${2:-ubuntu}"
    os_version="${3:-22.04}"
    hw_disk_bus="${4:-scsi}"

    upload_options="\
        --property architecture=x86_64 \
        --property hw_disk_bus='${hw_disk_bus}' \
        --property hw_scsi_model=virtio-scsi \
        --property hw_vif_multiqueue_enabled=true \
        --property hw_qemu_guest_agent=yes \
        --property os_require_quiesce=yes \
        --property os_type=linux \
        --property os_admin_user=root \
        --property os_distro='${os_distro}' \
        --property os_version='${os_version}'"

    id_file="${name}.id.txt"
    if [ -f "${id_file}" ]; then
        upload_options="${upload_options} --id '$(cat ${id_file})'"
    fi

    desc_file="${name}.desc.txt"
    if [ -f "${desc_file}" ]; then
        upload_options="${upload_options} --property description='$(cat ${desc_file})'"
    fi

    img_file="${name}.qcow2"
    if [ -f "${img_file}" ]; then
        upload_options="${upload_options} --disk-format qcow2"
    else
        img_file="${name}.img"
        if [ -f "${img_file}" ]; then
            upload_options="${upload_options} --disk-format raw"
        fi
    fi

    upload ${upload_options} --file "${img_file}" "${name}"
}

image-ubuntu() {
    image-linux "$1" "ubuntu" "$2" "$3"
}

image-centos() {
    os_version="${2:-7}"
    image-linux "$1" "centos" "${os_version}" "$3"
}
