#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

echo ">> Copy filebrowser file from HOST"

if [ -n "${FILEBROWSER_FILE}" ]; then
    cp ${FILEBROWSER_FILE} ${TMP_MOUNT_PATH}/tmp/filebrowser.tar.gz
else
    echo "ERROR: FILEBROWSER_FILE is not set."
fi
