#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Copy rvc_webui source file from HOST"

if [ -n "${RVC_WEBUI_FILE}" ]; then
    cp "${RVC_WEBUI_FILE}" "${TMP_MOUNT_PATH}/tmp/$(basename ${RVC_WEBUI_FILE})"
else
    echo "ERROR: RVC_WEBUI_FILE is not set."
fi

# if RVC_WEBUI_DATA_FILE is not "-", then copy the file to the image
if [ -n "${RVC_WEBUI_DATA_FILE}" ] && [ "${RVC_WEBUI_DATA_FILE}" != "-" ]; then
    echo ">> Copy RVC_WEBUI data file from HOST"
    cp "${RVC_WEBUI_DATA_FILE}" "${TMP_MOUNT_PATH}/${RVC_WEBUI_DATA_TAR}"
fi
