#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Install ${COMFYUI_APP_NAME}"

TAR_FILE=/tmp/$(basename ${COMFYUI_FILE})
tar -xvf ${TAR_FILE} -C /root/
rm -rf ${TAR_FILE}

ln -s "/usr/local/bin/${COMFYUI_START_SCRIPT}" "/root/${COMFYUI_START_SCRIPT}"

# if COMFYUI_DATA_LINK_FILE is not "-"
if [ -n "${COMFYUI_DATA_LINK_FILE}" ] && [ "${COMFYUI_DATA_LINK_FILE}" != "-" ]; then
    echo ">> link a COMFYUI data file on HOST"
    ln -s "${COMFYUI_DATA_LINK_FILE}" "${COMFYUI_DATA_TAR}"
fi

echo ">> install cudnn9"
sudo apt-get -y install \
    libcudnn9-cuda-12 \
    libcudnn9-dev-cuda-12 \
    ffmpeg
