#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo "############################################################"
echo "# ssh permit root login                                    #"
echo "############################################################"

cat >/etc/cloud/cloud.cfg.d/06-dib-root-pwauth.cfg <<EOF
runcmd:
  - sed -i 's/#PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
EOF
