#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Install sd-webui"

TAR_FILE=/tmp/$(basename ${SD_WEBUI_FILE})
tar -xvf ${TAR_FILE} -C /root/

ln -s /usr/local/bin/start_sd_webui /root/start_sd_webui
