#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

SYSTEMD_UNIT_FILE=/etc/systemd/system/sdwebui.service
cat <<EOF >${SYSTEMD_UNIT_FILE}
[Unit]
Description=Stable Diffusion Web UI
After=root-public.mount root-data.mount network-online.target
Wants=network-online.target

[Service]
Type=simple
PIDFile=/run/sdwebui.pid
User=root
WorkingDirectory=/root/
ExecStart=start_sd_webui --gradio-auth-path /root/.gradio.passwd.txt
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

# systemctl enable sdwebui.service
