#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

SCRIPTDIR="$(dirname $0)/../scripts"
TARGETDIR="${TMP_MOUNT_PATH}/tmp/scripts-install"

if [ ! -d "${TARGETDIR}" ]; then
    cp "${SCRIPTDIR}" "${TARGETDIR}"
fi
