#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
  set -x
fi
set -eu
set -o pipefail

echo ">> setup config openstack datasource"

if [ -d /etc/cloud/cloud.cfg.d ]; then
  cat >/etc/cloud/cloud.cfg.d/92-datasource-openstack.cfg <<EOF
datasource:
  OpenStack:
    metadata_urls: ["http://169.254.169.254"]
    max_wait: 60
    timeout: 10
    retries: 5
    apply_network_config: True
EOF
fi
