#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
  set -x
fi
set -o errexit
set -o nounset
set -o pipefail

# Configure RCON settings
mkdir -p ${INSTALL_BASE}/.config/rcon
cat <<EOF >${INSTALL_BASE}/.config/rcon/rcon.yaml
default:
  address: "127.0.0.1:${RCON_PORT}"
  password: "${RCON_PASSWORD}"
EOF
