#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

CRONTAB_FILE=/etc/cron.d/palworld
cat <<EOF >${CRONTAB_FILE}
# update on 02:00 every day
0 2 * * * /usr/local/bin/palworld-server update > /dev/null 2>&1
# backup on 03:00 every day
0 3 * * * /usr/local/bin/palworld-server backup > /dev/null 2>&1
EOF
