#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail


echo "#############################################################"
echo "# Miniconda3 Installation                                   #"
echo "#############################################################"

# download installer

mkdir -p /tmp/miniconda 
cd /tmp/miniconda 

if [ -n "${DIB_CONDA_URL}" ]; then
    wget -nv $DIB_CONDA_URL -o miniconda.sh
else
    echo "ERROR: DIB_CONDA_URL is not set."
fi

# Install conda
sh miniconda.sh -b -p /root/miniconda3/

# clean
rm -Rf /tmp/miniconda 
