#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

# Install Nvidia Container Toolkit
VERSION_STRING="${DIB_NVIDIA_CTK_VERSION}-1"

sudo apt-get install -y nvidia-container-toolkit=$VERSION_STRING

nvidia-ctk runtime configure --runtime=docker
