#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

if [ ! -f $DIB_MOFED_FILE ]; then
    wget "${DIB_MOFED_URL}" -O "$DIB_MOFED_FILE"
fi
