#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

echo "############################################################"
echo "# Copy Mellanox OFED ISO from HOST                         #"
echo "############################################################"

if [ -n "${DIB_MOFED_FILE}" ]; then
    cp ${DIB_MOFED_FILE} ${TMP_MOUNT_PATH}/tmp/
else
    echo "ERROR: DIB_MOFED_FILE is not set."
fi