#!/bin/bash

upload() {
    openstack image create \
        --container-format bare \
        --disk-format qcow2 \
        --progress \
        --public $@
}

image-ubuntu() {
    name="$1"
    os_version="${2:-22.04}"
    upload \
        --property hw_qemu_guest_agent=yes \
        --property os_admin_user=root \
        --property os_type=linux \
        --property os_distro=ubuntu \
        --property os_version="${os_version}" \
        --id "$(cat ${name}.id.txt)" \
        --file "${name}.qcow2" \
        "${name}"
}
