#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo ">> enable root login"

cat >/etc/cloud/cloud.cfg.d/05-dib-root-login.cfg <<EOF
# enable root login
disable_root: false
EOF
