#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Copy ${COMFYUI_APP_NAME} source file from HOST"

if [ -n "${COMFYUI_FILE}" ]; then
    cp "${COMFYUI_FILE}" "${TMP_MOUNT_PATH}/tmp/$(basename ${COMFYUI_FILE})"
else
    echo "ERROR: COMFYUI_FILE is not set."
    exit 1
fi

# if COMFYUI_DATA_FILE is not "-", then copy the file to the image
if [ -n "${COMFYUI_DATA_FILE}" ] && [ "${COMFYUI_DATA_FILE}" != "-" ]; then
    echo ">> Copy COMFYUI data file from HOST"
    cp "${COMFYUI_DATA_FILE}" "${TMP_MOUNT_PATH}/${COMFYUI_DATA_TAR}"
fi
