#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Download fuse if it not exists"

if [ ! -f $FUSE_FILE ]; then
    curl -sfL -o "$FUSE_FILE" "${FUSE_URL}"
else
    echo "$FUSE_FILE already exists."
fi
