#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Copy sd_webui source file from HOST"

if [ -n "${SD_WEBUI_FILE}" ]; then
    cp "${SD_WEBUI_FILE}" "${TMP_MOUNT_PATH}/tmp/$(basename ${SD_WEBUI_FILE})"
else
    echo "ERROR: SD_WEBUI_FILE is not set."
fi

# if SD_WEBUI_DATA_FILE is not "-", then copy the file to the image
DEFAULT_SD_WEBUI_DATA_TAR="/root/sd_webui_data.tar"
if [ -n "${SD_WEBUI_DATA_FILE}" ] && [ "${SD_WEBUI_DATA_FILE}" != "-" ]; then
    echo ">> Copy sd_webui data file from HOST"
    cp "${SD_WEBUI_DATA_FILE}" "${TMP_MOUNT_PATH}/${DEFAULT_SD_WEBUI_DATA_TAR}"
fi
