#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

cat <<EOF >/etc/systemd/system/jupyter-lab.service
[Unit]
Description=Jupyter Lab

[Service]
Type=simple
PIDFile=/run/jupyter-lab.pid
ExecStart=/usr/local/bin/jupyter lab --allow-root --config /root/.jupyter/jupyter_server_config.py
User=root
WorkingDirectory=/root/
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

systemctl enable jupyter-lab.service
