#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

# ref: https://docs.openwebui.com/getting-started/#how-to-install-without-docker

cd /root

git clone https://github.com/open-webui/open-webui.git
cd open-webui/
git checkout "v${OPENWEBUI_VERSION}"

# Copying required .env file
cp -RPp .env.example .env

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Building Frontend Using Node
npm i
npm run build

# install python dependencies
start_open_webui --install-only
