#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Install ${FOOOCUS_APP_NAME}"

TAR_FILE=/tmp/$(basename ${FOOOCUS_FILE})
tar -xvf ${TAR_FILE} -C /root/

ln -s "/usr/local/bin/${FOOOCUS_START_SCRIPT}" "/root/${FOOOCUS_START_SCRIPT}"

# if FOOOCUS_DATA_LINK_FILE is not "-"
if [ -n "${FOOOCUS_DATA_LINK_FILE}" ] && [ "${FOOOCUS_DATA_LINK_FILE}" != "-" ]; then
    echo ">> link data file on HOST"
    ln -s "${FOOOCUS_DATA_LINK_FILE}" "${FOOOCUS_DATA_TAR}"
fi
