#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

CONDA_PREFIX=$(conda info --base)
python3() {
    $CONDA_PREFIX/bin/python3 "$@"
}

## Install TensorFlow
python3 -m pip install tensorflow==${TENSORFLOW_VER}

## (optional) Install TensorRT
python3 -m pip install tensorrt==${TENSORRT_VER}
