#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Install rvc-webui"

TAR_FILE=/tmp/$(basename ${RVC_WEBUI_FILE})
tar -xvf ${TAR_FILE} -C /root/

ln -s "/usr/local/bin/${RVC_WEBUI_START_SCRIPT}" "/root/${RVC_WEBUI_START_SCRIPT}"

# if RVC_WEBUI_DATA_LINK_FILE is not "-"
if [ -n "${RVC_WEBUI_DATA_LINK_FILE}" ] && [ "${RVC_WEBUI_DATA_LINK_FILE}" != "-" ]; then
    echo ">> link a RVC_WEBUI data file on HOST"
    ln -s "${RVC_WEBUI_DATA_LINK_FILE}" "${RVC_WEBUI_DATA_TAR}"
fi
