#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Copy ${FOOOCUS_APP_NAME} source file from HOST"

if [ -n "${FOOOCUS_FILE}" ]; then
    cp "${FOOOCUS_FILE}" "${TMP_MOUNT_PATH}/tmp/$(basename ${FOOOCUS_FILE})"
else
    echo "ERROR: FOOOCUS_FILE is not set."
fi

# if FOOOCUS_DATA_FILE is not "-", then copy the file to the image
if [ -n "${FOOOCUS_DATA_FILE}" ] && [ "${FOOOCUS_DATA_FILE}" != "-" ]; then
    echo ">> Copy COMFYUI data file from HOST"
    cp "${FOOOCUS_DATA_FILE}" "${TMP_MOUNT_PATH}/${FOOOCUS_DATA_TAR}"
fi
