#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Copy prometheus file from HOST"

if [ -n "${PROMETHEUS_FILE}" ]; then
    cp ${PROMETHEUS_FILE} ${TMP_MOUNT_PATH}/tmp/prometheus.tar.gz
else
    echo "ERROR: PROMETHEUS_FILE is not set."
fi
