#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Install minfs"

# install dpkg
sudo dpkg -i /tmp/$(basename ${MINFS_FILE})

# create dir for config
mkdir -p /etc/minfs/
