#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

ln -s /etc/nginx/sites-available/comfyui.conf /etc/nginx/sites-enabled/

# will not start nginx on first boot
systemctl disable nginx.service
