#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo "############################################################"
echo "# install jupyter using conda                              #"
echo "############################################################"

if [ -n "${DIB_JUPYTERLAB_VER}" ]; then
    conda install -y -c conda-forge jupyterlab=${DIB_JUPYTERLAB_VER}
else
    conda install -y -c conda-forge jupyterlab
fi

JP_PATH=$(conda run which jupyter)
ln -s $JP_PATH /usr/local/bin/jupyter
