#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Install ${QINGLONG_APP_NAME}"

TAR_FILE=/tmp/$(basename ${QINGLONG_FILE})
tar -xvf ${TAR_FILE} -C /root/
rm -rf ${TAR_FILE}
