#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

install_nvidia_driver() {
    major_version=${NVIDIA_DRIVER_VERSION%%.*}
    sudo apt-get -y install --no-install-recommends \
        nvidia-driver-${major_version}=${NVIDIA_DRIVER_VERSION}-0ubuntu1
}

install_nvidia_driver
echo "Nvidia Driver ${NVIDIA_DRIVER_VERSION} installed"
