#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

CONDA_PREFIX=$(conda info --base)
python3() {
    $CONDA_PREFIX/bin/python3 "$@"
}

for f in /opt/scripts-install/helpers/*; do
    source $f
done
install_pytorch
