#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

echo ">> Download node-exporter if it not exists"

if [ ! -f $DIB_NODE_EXPORTER_FILE ]; then
    curl -sfL -o "$DIB_NODE_EXPORTER_FILE" "${DIB_NODE_EXPORTER_URL}"
else
    echo "$DIB_NODE_EXPORTER_FILE already exists."
fi
