#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

echo ">> Copy node-exporter file from HOST"

if [ -n "${DIB_NODE_EXPORTER_FILE}" ]; then
    cp ${DIB_NODE_EXPORTER_FILE} ${TMP_MOUNT_PATH}/tmp/node-exporter.tar.gz
else
    echo "ERROR: DIB_NODE_EXPORTER_FILE is not set."
fi