#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

# Disable default motd
chmod -x /etc/update-motd.d/*

# Remove motd-new.service
systemctl disable motd-news.service
rm /lib/systemd/system/motd-news.service
