#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Download minfs if it not exists"

if [ ! -f "$MINFS_FILE" ]; then
    curl -sfL -o "$MINFS_FILE" "$MINFS_URL"
else
    echo "$MINFS_FILE already exists."
fi
