#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Copy minfs file from HOST"

if [ -n "${MINFS_FILE}" ]; then
    cp ${MINFS_FILE} ${TMP_MOUNT_PATH}/tmp/$(basename ${MINFS_FILE})
else
    echo "ERROR: MINFS_FILE is not set."
fi
