#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

version_short() {
    echo $1 | awk -F'.' '{print $1 "." $2}'
}

install_cuda_driver() {
    major_version=${CUDA_DRIVER_VERSION%%.*}
    sudo apt-get -y install --no-install-recommends \
        cuda-drivers-${major_version}=${CUDA_DRIVER_VERSION}-1
}

freeze_cuda_driver() {
    major_version=${CUDA_DRIVER_VERSION%%.*}
    # prevent nvidia driver from being upgraded
    sudo apt-mark hold cuda-drivers-${major_version}
}

# https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#common-installation-instructions-for-ubuntu
install_cuda_toolkit() {
    cuda_version=$(version_short $CUDA_VERSION)
    sudo apt-get -y install \
        cuda-toolkit-${cuda_version//./-}=$CUDA_VERSION-1
    sudo apt-get -y install \
        nvidia-gds-${cuda_version//./-}=$CUDA_VERSION-1
}

install_cudnn() {
    cuda_version=$(version_short $CUDA_VERSION)
    sudo apt-get -y install \
        libcudnn8=$CUDNN_VERSION-1+cuda${cuda_version} \
        libcudnn8-dev=$CUDNN_VERSION-1+cuda${cuda_version}
}

add_path() {
    echo 'PATH="$PATH:/usr/local/cuda/bin"' >/etc/profile.d/099_cuda.sh
    chmod +x /etc/profile.d/099_cuda.sh
}

# all in one
install_all() {
    install_cuda_driver
    freeze_cuda_driver
    echo "CUDA driver ${CUDA_DRIVER_VERSION} installed"
    install_cuda_toolkit
    echo "CUDA toolkit ${CUDA_VERSION} installed"
    install_cudnn
    echo "cuDNN ${CUDNN_VERSION} installed"
    add_path
    echo "add cuda bin to PATH"
}

install_all
