#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -euo pipefail

echo ">> Install fuse build tools"
apt-get -y install meson

echo ">> Install fuse"
tar -xvf "$FUSE_FILE" -C /tmp
cd /tmp/libfuse-fuse-${FUSE_VERSION}
mkdir build; cd build
meson setup ..
ninja
sudo ninja install
