#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

echo "############################################################"
echo "# enable root ssh login                                    #"
echo "############################################################"

# remove default user
sed -i "/users:/,3d" /etc/cloud/cloud.cfg

# enable root login
sed -i "s\disable_root: true\disable_root: false\g" /etc/cloud/cloud.cfg
