#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

curl -o ${MINICONDA_INSTALLER_LOCAL} ${MINICONDA_INSTALLER_URL} && chmod 0755 ${MINICONDA_INSTALLER_LOCAL}
