#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo ">> install hcp"

curl -sfL -o "/usr/local/bin/hcp" "${HCP_REPO}/hcp-${HCP_VERSION}"
chmod +x "/usr/local/bin/hcp"
