#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo ">> install hcp"

cd /tmp
wget --content-disposition "${QEMU_GA_CM_URL}"
QEMU_GA_CM_FILE=$(ls -l /tmp/ | grep "qemu_guest_agent" | awk '{print $9}')
unzip ${QEMU_GA_CM_FILE}

echo ">> stop qemu-guest-agent"
systemctl stop qemu-guest-agent

echo ">> install qemu-guest-agent-cm"
QEMU_GA_CM_DIR=$(ls -l /tmp/ | grep "qemu-guest-agent" | awk '{print $9}')
mv /usr/bin/qemu-ga /usr/bin/qemu-ga.bak
mv ${QEMU_GA_CM_DIR}/ubuntu/x86/64bit/qemu-ga /usr/bin/qemu-ga
chmod a+x /usr/bin/qemu-ga
