#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -x "$MINICONDA_INSTALLER_LOCAL" ]; then
    bash $MINICONDA_INSTALLER_LOCAL -b -f -p $MINICONDA_ROOT || exit -1
fi

ln -s $MINICONDA_ROOT/bin/conda /usr/local/bin/conda
conda init
conda --version

if [ -n "${MINICONDA_BASE_PYTHON_VERSION}" ] && [ "${MINICONDA_BASE_PYTHON_VERSION}" != "-" ]; then
    echo ">> change base python version to ${MINICONDA_BASE_PYTHON_VERSION}"
    conda install python=${MINICONDA_BASE_PYTHON_VERSION} -y
    python -V
fi
